# Week 1
## Day 2
### Eigenvalues & Eigenvectors by Hand


In [3]:
import numpy as np

A = np.array([
  [4 , 1 , 2],
  [1 , 5 , 1],
  [2 , 1 , 7]
], dtype = float)

eigenvalues , eigenvectors = np.linalg.eig(A)

for i in range(len(eigenvalues)):
  lam = eigenvalues[i]  #lambda in the formula
  v = eigenvectors[: , i]

  lhs = A @ v
  rhs = lam * v

  print(f"EigenValue {i}: matches = {np.allclose(lhs, rhs)}")



EigenValue 0: matches = True
EigenValue 1: matches = True
EigenValue 2: matches = True


### Connect to PCA via the Iris Dataset

In [12]:
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA

# iris = load_data()
# X = iris.data
X = load_iris().data  # 150 samples, 4 features i.e. 150 rows and 4 columns


# Center the data (subtract the mean of each column)
X_centered = X - X.mean(axis = 0)

# Compute the covariance matrix by hand:
cov_matrix = (X_centered.T @ X_centered) / (X_centered.shape[0] - 1)

# Get its eigenvectors:
eigvals, eigvecs = np.linalg.eig(cov_matrix)

order = np.argsort(eigvals)[::-1]
eigvals_sorted = eigvals[order]
eigvecs_sorted = eigvecs[:, order]

pca = PCA(n_components=4)
pca.fit(X)

print(pca.components_)   # sklearn's principal components

#real because it prints +0.j which is imaginary part 
print(eigvecs_sorted.T.real)          # your manually sorted and computed ones



[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [ 0.65658877  0.73016143 -0.17337266 -0.07548102]
 [-0.58202985  0.59791083  0.07623608  0.54583143]
 [ 0.31548719 -0.3197231  -0.47983899  0.75365743]]
[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [-0.65658877 -0.73016143  0.17337266  0.07548102]
 [-0.58202985  0.59791083  0.07623608  0.54583143]
 [ 0.31548719 -0.3197231  -0.47983899  0.75365743]]
